"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { contentLocales, localeRegistry, type ContentLocale } from "./locales";

type Locale = "en" | "zh";
type SeoLocale = ContentLocale;
type SeoRecord = { id: string; path: string; locale: SeoLocale; status: "draft" | "published"; title: string; description: string; keywords: string[]; updatedBy: string };
type AdminUser = { id: string; email: string; role: "admin" | "marketing" | "sales" | "editor"; active: boolean | number };

function AdminSignIn({ locale, route, error }: { locale: Locale; route: string; error: string }) {
  if (error !== "Authentication required") return null;
  return <section className="admin-state" role="alert"><h2>{locale === "zh" ? "请先登录，再访问这个管理区域。" : "Sign in before opening this administration area."}</h2><Link className="button button-dark" href={`/signin-with-chatgpt?return_to=${encodeURIComponent(`/${locale}${route}`)}`}>{locale === "zh" ? "使用 ChatGPT 登录" : "Sign in with ChatGPT"}</Link></section>;
}

export function AdminSeo({ locale }: { locale: Locale }) {
  const [records, setRecords] = useState<SeoRecord[]>([]);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [form, setForm] = useState({ path: "/", locale: "en" as SeoLocale, status: "draft" as "draft" | "published", title: "", description: "", keywords: "" });
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  const [saving, setSaving] = useState(false);
  const load = async () => { const response = await fetch("/api/admin/seo"); const result = await response.json() as { records?: SeoRecord[]; error?: string }; if (!response.ok) throw new Error(result.error || "Unable to load SEO records"); setRecords(result.records || []); };
  useEffect(() => { const controller = new AbortController(); fetch("/api/admin/seo", { signal: controller.signal }).then(async response => { const result = await response.json() as { records?: SeoRecord[]; error?: string }; if (!response.ok) throw new Error(result.error || "Unable to load SEO records"); setRecords(result.records || []); }).catch(loadError => { if (loadError instanceof DOMException && loadError.name === "AbortError") return; setError(loadError instanceof Error ? loadError.message : "Unable to load SEO records"); }); return () => controller.abort(); }, []);
  const select = (record: SeoRecord) => { setSelectedId(record.id); setForm({ path: record.path, locale: record.locale, status: record.status, title: record.title, description: record.description, keywords: record.keywords.join(", ") }); setMessage(""); setError(""); };
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setMessage(""); setError(""); try { const response = await fetch(`/api/admin/seo${selectedId ? `/${selectedId}` : ""}`, { method: selectedId ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, keywords: form.keywords.split(",").map(value => value.trim()).filter(Boolean) }) }); const result = await response.json() as { error?: string; id?: string }; if (!response.ok) throw new Error(result.error || "Unable to save SEO record"); await load(); setSelectedId(result.id || selectedId); setMessage(locale === "zh" ? "SEO 设置已保存。" : "SEO settings saved."); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Unable to save SEO record"); } finally { setSaving(false); } };
  if (error === "Authentication required") return <AdminSignIn locale={locale} route="/admin/seo" error={error}/>;
  return <section className="settings-workspace"><aside className="settings-list"><button className="button button-dark" type="button" onClick={() => { setSelectedId(null); setForm({ path: "/", locale: "en", status: "draft", title: "", description: "", keywords: "" }); }}>{locale === "zh" ? "新建 SEO 设置" : "New SEO entry"}</button>{records.map(record => <button key={record.id} type="button" className={record.id === selectedId ? "active" : ""} onClick={() => select(record)}><b>{record.path}</b><span>{record.locale} · {record.status}</span><small>{record.title}</small></button>)}</aside><form className="settings-editor" onSubmit={save}><div className="editor-grid"><label><span>Public path</span><input required value={form.path} onChange={event => setForm(current => ({ ...current, path: event.target.value }))}/></label><label><span>Locale</span><select value={form.locale} onChange={event => setForm(current => ({ ...current, locale: event.target.value as SeoLocale }))}>{contentLocales.map(item => <option key={item} value={item}>{localeRegistry[item].nativeLabel}</option>)}</select></label><label><span>Status</span><select value={form.status} onChange={event => setForm(current => ({ ...current, status: event.target.value as "draft" | "published" }))}><option value="draft">Draft</option><option value="published">Published</option></select></label></div><label><span>Meta title</span><input required maxLength={160} value={form.title} onChange={event => setForm(current => ({ ...current, title: event.target.value }))}/></label><label><span>Meta description</span><textarea required maxLength={320} value={form.description} onChange={event => setForm(current => ({ ...current, description: event.target.value }))}/></label><label><span>Keywords — comma separated</span><input value={form.keywords} onChange={event => setForm(current => ({ ...current, keywords: event.target.value }))}/></label>{form.status === "published" && <p className="publishing-warning">{locale === "zh" ? "发布后，该设置会覆盖页面默认 SEO 信息。" : "Publishing makes this entry override the page's default SEO metadata."}</p>}{error && <p className="form-message error" role="alert">{error}</p>}{message && <p className="form-message success" role="status">{message}</p>}<button className="button button-dark" type="submit" disabled={saving}>{saving ? (locale === "zh" ? "正在保存…" : "Saving…") : (locale === "zh" ? "保存 SEO" : "Save SEO")}</button></form></section>;
}

export function AdminUsers({ locale }: { locale: Locale }) {
  const [users, setUsers] = useState<AdminUser[]>([]);
  const [bootstrapAdmins, setBootstrapAdmins] = useState<string[]>([]);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [form, setForm] = useState({ email: "", role: "editor" as AdminUser["role"], active: true });
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  const [saving, setSaving] = useState(false);
  const load = async () => { const response = await fetch("/api/admin/users"); const result = await response.json() as { users?: AdminUser[]; bootstrapAdmins?: string[]; error?: string }; if (!response.ok) throw new Error(result.error || "Unable to load users"); setUsers(result.users || []); setBootstrapAdmins(result.bootstrapAdmins || []); };
  useEffect(() => { const controller = new AbortController(); fetch("/api/admin/users", { signal: controller.signal }).then(async response => { const result = await response.json() as { users?: AdminUser[]; bootstrapAdmins?: string[]; error?: string }; if (!response.ok) throw new Error(result.error || "Unable to load users"); setUsers(result.users || []); setBootstrapAdmins(result.bootstrapAdmins || []); }).catch(loadError => { if (loadError instanceof DOMException && loadError.name === "AbortError") return; setError(loadError instanceof Error ? loadError.message : "Unable to load users"); }); return () => controller.abort(); }, []);
  const select = (user: AdminUser) => { setSelectedId(user.id); setForm({ email: user.email, role: user.role, active: Boolean(user.active) }); setMessage(""); setError(""); };
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setMessage(""); setError(""); try { const response = await fetch(`/api/admin/users${selectedId ? `/${selectedId}` : ""}`, { method: selectedId ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const result = await response.json() as { error?: string; id?: string }; if (!response.ok) throw new Error(result.error || "Unable to save user"); await load(); setSelectedId(result.id || selectedId); setMessage(locale === "zh" ? "管理员权限已保存。" : "Admin access saved."); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Unable to save user"); } finally { setSaving(false); } };
  if (error === "Authentication required") return <AdminSignIn locale={locale} route="/admin/users" error={error}/>;
  return <section className="settings-workspace"><aside className="settings-list"><button className="button button-dark" type="button" onClick={() => { setSelectedId(null); setForm({ email: "", role: "editor", active: true }); }}>{locale === "zh" ? "添加管理员" : "Add admin user"}</button>{bootstrapAdmins.length > 0 && <div className="bootstrap-admins"><span>{locale === "zh" ? "环境超级管理员" : "Environment super admins"}</span>{bootstrapAdmins.map(email => <small key={email}>{email}</small>)}</div>}{users.map(user => <button key={user.id} type="button" className={user.id === selectedId ? "active" : ""} onClick={() => select(user)}><b>{user.email}</b><span>{user.role} · {user.active ? "active" : "inactive"}</span></button>)}</aside><form className="settings-editor" onSubmit={save}><label><span>Account email</span><input required type="email" value={form.email} onChange={event => setForm(current => ({ ...current, email: event.target.value }))}/></label><label><span>Role</span><select value={form.role} onChange={event => setForm(current => ({ ...current, role: event.target.value as AdminUser["role"] }))}><option value="admin">Admin</option><option value="marketing">Marketing</option><option value="sales">Sales</option><option value="editor">Editor</option></select></label><label className="check-field"><input type="checkbox" checked={form.active} onChange={event => setForm(current => ({ ...current, active: event.target.checked }))}/><span>{locale === "zh" ? "账号可用" : "Account active"}</span></label><div className="role-guide"><b>{locale === "zh" ? "权限说明" : "Role permissions"}</b><p>Admin — all content, publishing, inquiries and users</p><p>Marketing — content publishing and inquiry review</p><p>Sales — inquiry pipeline and content read access</p><p>Editor — draft and review content, without publishing</p></div>{error && <p className="form-message error" role="alert">{error}</p>}{message && <p className="form-message success" role="status">{message}</p>}<button className="button button-dark" type="submit" disabled={saving}>{saving ? (locale === "zh" ? "正在保存…" : "Saving…") : (locale === "zh" ? "保存权限" : "Save access")}</button></form></section>;
}
