import Link from "next/link";
import { applications, articles, company, products } from "./site-data";

const Arrow = () => <span aria-hidden="true">↗</span>;

function Placeholder({ children }: { children: React.ReactNode }) {
  return <span className="placeholder">Review needed: {children}</span>;
}

function Header() {
  return <>
    <div className="review-bar">PRE-LAUNCH REVIEW SITE <span>Unverified company facts are clearly marked</span></div>
    <header className="header"><Link className="brand" href="/"><span className="brand-mark">T</span><span>TNV <b>CHEMICALS</b></span></Link>
      <nav aria-label="Primary navigation"><Link href="/products">Products</Link><Link href="/applications">Applications</Link><Link href="/quality-compliance">Quality</Link><Link href="/technical-library">Resources</Link><Link href="/about">Company</Link></nav>
      <Link className="button button-small" href="/request-quote">Request a quote <Arrow /></Link>
    </header>
  </>;
}

function Footer() {
  return <footer><div className="footer-top"><div><div className="brand brand-light"><span className="brand-mark">T</span><span>TNV <b>CHEMICALS</b></span></div><p>Application-led ink and chemical solutions for international industrial buyers.</p></div><div><h3>Explore</h3><Link href="/products">Products</Link><Link href="/applications">Applications</Link><Link href="/insights">Insights</Link></div><div><h3>Company</h3><Link href="/about">About</Link><Link href="/quality-compliance">Quality & compliance</Link><Link href="/contact">Contact</Link></div><div><h3>Contact</h3><p><Placeholder>sales email</Placeholder></p><p><Placeholder>phone / WhatsApp</Placeholder></p></div></div><div className="footer-bottom"><span>© 2026 TNV Chemicals. Pre-launch content.</span><span><Link href="/privacy-policy">Privacy</Link> · <Link href="/terms">Terms</Link></span></div></footer>;
}

function ProductCard({ product }: { product: typeof products[number] }) {
  return <Link className="product-card" href={`/products/${product.category}/${product.slug}`}><div className="product-code">{product.code}</div><h3>{product.name}</h3><p>{product.use}</p><div className="card-link">View product <Arrow /></div></Link>;
}

function Rfq({ compact = false }: { compact?: boolean }) {
  return <section className={compact ? "rfq rfq-compact" : "rfq"}><div><span className="eyebrow">START A TECHNICAL CONVERSATION</span><h2>Tell us what your production line needs.</h2><p>Share your substrate, print method, target performance and estimated volume. A technical sales contact can then qualify the right next step.</p></div><form aria-label="Request a quote form"><label>Business email<input required type="email" placeholder="name@company.com" /></label><label>Product or application<select defaultValue=""><option value="" disabled>Select an area</option><option>Printing inks</option><option>Colorants & concentrates</option><option>Functional additives</option><option>Custom formulation</option></select></label>{!compact && <><label>Company<input required placeholder="Company name" /></label><label>Country<input required placeholder="Country / market" /></label><label className="full">Production requirement<textarea rows={4} placeholder="Substrate, print method, current issue, target performance and monthly quantity" /></label></>}<button type="submit" className="button">Prepare inquiry <Arrow /></button><small>Demo form — recipient inbox and privacy workflow must be connected before launch.</small></form></section>;
}

function Home() {
  return <>
    <main>
      <section className="hero"><div className="hero-copy"><span className="eyebrow">PRINTING INKS · FUNCTIONAL MATERIALS · CUSTOM FORMULATION</span><h1>Industrial chemistry,<br /><em>built around your process.</em></h1><p>Application-led ink and chemical solutions for packaging, paper and specialty print buyers—from initial sample to repeatable production.</p><div className="hero-actions"><Link className="button" href="/products">Explore products <Arrow /></Link><Link className="text-link" href="/request-quote">Discuss an application <Arrow /></Link></div><div className="hero-trust"><span><b>01</b> Buyer-first technical qualification</span><span><b>02</b> Custom color & formulation pathway</span><span><b>03</b> Export documentation support</span></div></div><div className="hero-panel"><div className="molecule-orbit orbit-one"></div><div className="molecule-orbit orbit-two"></div><div className="formula-card"><span>APPLICATION NOTE / 01</span><b>Substrate + process + end-use</b><p>The three inputs behind every useful recommendation.</p></div><div className="batch-card"><span>BATCH TRACEABILITY</span><div><i></i><i></i><i></i><i></i><i></i><i></i></div><small><Placeholder>verified workflow details</Placeholder></small></div></div></section>
      <section className="proof-strip"><span>FORMULATION SUPPORT</span><span>COLOR MATCHING</span><span>LAB SAMPLE PATHWAY</span><span>DOCUMENTATION READY</span></section>
      <section className="section"><div className="section-head"><div><span className="eyebrow">PRODUCT FAMILIES</span><h2>Start with the chemistry.<br />Finish with the application.</h2></div><p>Browse representative product families. All technical values remain clearly marked until the company supplies verified specifications.</p></div><div className="product-grid">{products.slice(0, 4).map(p => <ProductCard key={p.slug} product={p} />)}</div><Link className="text-link dark" href="/products">View all products <Arrow /></Link></section>
      <section className="dark-section"><div className="section-head"><div><span className="eyebrow">APPLICATION-FIRST SELECTION</span><h2>What are you printing?</h2></div><p>Buyers do not always begin with a product code. These pathways start with the substrate, print process and performance target.</p></div><div className="application-grid">{applications.map((a, i) => <Link href={`/applications/${a.slug}`} key={a.slug}><span>0{i + 1}</span><h3>{a.name}</h3><p>{a.intro}</p><b>Explore application <Arrow /></b></Link>)}</div></section>
      <section className="section split"><div><span className="eyebrow">EVIDENCE, NOT EMPTY CLAIMS</span><h2>A technical resource center buyers can actually use.</h2><p>Certificates, specifications and test reports belong in a clear, versioned library—not buried inside sales copy.</p><Link className="button button-dark" href="/technical-library">Open technical library <Arrow /></Link></div><div className="document-stack"><div><span>TDS</span><b>Technical Data Sheet</b><small>Specification by product grade</small></div><div><span>SDS</span><b>Safety Data Sheet</b><small>Market and language specific</small></div><div><span>COA</span><b>Certificate of Analysis</b><small>Batch-level documentation</small></div><Placeholder>documents pending company upload</Placeholder></div></section>
      <section className="insights section"><div className="section-head"><div><span className="eyebrow">TECHNICAL INSIGHTS</span><h2>Useful answers for industrial buyers.</h2></div><Link className="text-link dark" href="/insights">View all insights <Arrow /></Link></div><div className="article-grid">{articles.map(a => <Link key={a.slug} href={`/insights/${a.slug}`}><span>{a.type}</span><h3>{a.title}</h3><p>{a.summary}</p><b>Read guide <Arrow /></b></Link>)}</div></section>
      <Rfq compact />
    </main>
  </>;
}

function ProductsPage() { return <main><PageHero eyebrow="PRODUCT CENTER" title="Formulations for real production conditions." intro="Explore representative product families, then qualify the exact grade around substrate, press, process and end-use requirements." /><section className="section"><div className="product-grid">{products.map(p => <ProductCard key={p.slug} product={p} />)}</div><div className="review-note"><b>Company review checkpoint</b><p>Product names and families shown here are structured placeholder content. Confirm the real catalog, codes, packaging, MOQ and technical limits before launch.</p></div></section><Rfq compact /></main>; }

function ProductDetail({ product }: { product: typeof products[number] }) { return <main><section className="product-hero"><div><div className="breadcrumbs"><Link href="/products">Products</Link> / {product.categoryName}</div><span className="eyebrow">{product.code}</span><h1>{product.name}</h1><p>{product.use}</p><div className="hero-actions"><Link className="button" href="/request-quote">Request this product <Arrow /></Link><a className="text-link" href="#specifications">View specifications ↓</a></div></div><div className="product-visual"><span>{product.code}</span><b>FORMULATION<br />WINDOW</b><div className="scale"><i></i><i></i><i></i><i></i><i></i></div><small>Final grade subject to technical qualification</small></div></section><section className="section product-content"><div><span className="eyebrow">WHY THIS FAMILY</span><h2>Built to be qualified, not guessed.</h2><p>This placeholder page demonstrates the buying information architecture. The final recommendation should follow a review of the customer’s substrate, equipment, speed, drying, finishing and resistance targets.</p><ul className="benefit-list">{product.benefits.map(b => <li key={b}>{b}</li>)}</ul></div><div id="specifications"><h2>Technical overview</h2><table><tbody>{product.specs.map(([k, v]) => <tr key={k}><th>{k}</th><td>{v}</td></tr>)}</tbody></table><div className="download-row"><button disabled>TDS — pending</button><button disabled>SDS — pending</button><button disabled>COA — on request</button></div></div></section><section className="faq section"><span className="eyebrow">BUYER FAQ</span><h2>Before you request a sample</h2><details><summary>What information is needed for grade selection?</summary><p>Share substrate, print method, press speed, drying setup, finishing process, target resistance and current production issue.</p></details><details><summary>Can the formulation and color be customized?</summary><p>Customization is presented as a capability pathway here, but its actual scope, MOQ and lead time require company confirmation.</p></details><details><summary>Which documents are available?</summary><p>TDS, SDS and batch documents should only be published after verified company files have been supplied and reviewed.</p></details></section><Rfq /></main>; }

function PageHero({ eyebrow, title, intro }: { eyebrow: string; title: string; intro: string }) { return <section className="page-hero"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{intro}</p></section>; }

function ApplicationsPage() { return <main><PageHero eyebrow="APPLICATIONS" title="Choose by substrate and process." intro="An application-led route helps buyers reach the right product family even when they do not know the precise chemical or grade name."/><section className="section application-list">{applications.map((a, i) => <Link href={`/applications/${a.slug}`} key={a.slug}><span>0{i+1}</span><div><h2>{a.name}</h2><p>{a.intro}</p></div><Arrow /></Link>)}</section><Rfq compact /></main>; }

function ApplicationDetail({ item }: { item: typeof applications[number] }) { const related = products.filter(p => p.category === "printing-inks").slice(0,3); return <main><PageHero eyebrow="APPLICATION GUIDE" title={item.name} intro={item.intro}/><section className="section product-content"><div><span className="eyebrow">COMMON BUYER CHALLENGES</span><h2>Define the production window first.</h2><ul className="benefit-list">{item.challenges.map(x => <li key={x}>{x}</li>)}</ul></div><div><span className="eyebrow">QUALIFICATION INPUTS</span><h2>Prepare these details</h2><table><tbody><tr><th>Substrate</th><td>Material, supplier and surface treatment</td></tr><tr><th>Process</th><td>Print method, speed and drying configuration</td></tr><tr><th>End use</th><td>Resistance, finishing and regulatory requirements</td></tr></tbody></table></div></section><section className="section"><div className="section-head"><div><span className="eyebrow">RELATED STARTING POINTS</span><h2>Representative product families</h2></div></div><div className="product-grid">{related.map(p => <ProductCard key={p.slug} product={p}/>)}</div></section><Rfq /></main>; }

function StandardPage({ route }: { route: string }) {
  const content: Record<string, [string,string,string]> = {
    "/custom-solutions": ["CUSTOM SOLUTIONS","A formulation pathway built around your line.","From application briefing and lab sample to production validation, the process should be documented, measurable and commercially clear."],
    "/quality-compliance": ["QUALITY & COMPLIANCE","Evidence buyers can verify.","This section is ready for the company’s real quality workflow, laboratory equipment, certifications, traceability evidence and export documentation."],
    "/technical-library": ["TECHNICAL LIBRARY","The documents behind the product.","A structured home for catalogs, TDS, SDS, certificates, test reports, color cards and packaging information."],
    "/about": ["ABOUT TNV CHEMICALS","Manufacturing context, stated precisely.","Company history, legal identity, location, ownership, capabilities and market experience will be published only after verification."],
    "/about/factory": ["FACTORY","Show the production environment.","A future evidence page for facility photography, production lines, equipment, workflow and verified capacity."],
    "/about/research-development": ["RESEARCH & DEVELOPMENT","From application question to tested formulation.","A future evidence page for laboratory workflow, sampling, test methods, technical team and documented product development."],
    "/about/quality-control": ["QUALITY CONTROL","Control from incoming material to final batch.","A future evidence page for inspection stages, batch records, retention samples, testing and release criteria."],
    "/contact": ["CONTACT","Start with the application.","Send your substrate, process, target performance and buying requirements so the right technical conversation can begin."],
    "/request-quote": ["REQUEST A QUOTE","Make your inquiry useful from the first message.","The more production context you provide, the faster a supplier can qualify product family, sample route, MOQ and lead time."],
    "/privacy-policy": ["LEGAL","Privacy policy.","This draft must be reviewed for the company’s legal entity, data collection, analytics, inquiry handling, retention and international transfer practices."],
    "/terms": ["LEGAL","Website terms.","This draft must be reviewed for the company’s legal identity, jurisdiction, technical information disclaimers and document usage rules."],
  };
  const [eyebrow,title,intro] = content[route] || content["/about"];
  if (route === "/request-quote" || route === "/contact") return <main><PageHero eyebrow={eyebrow} title={title} intro={intro}/><Rfq/></main>;
  if (route === "/technical-library") return <main><PageHero eyebrow={eyebrow} title={title} intro={intro}/><section className="section library-grid">{["Product catalog","Technical data sheets","Safety data sheets","Certificates","Testing reports","Packaging information"].map(x => <div key={x}><span>PDF</span><h2>{x}</h2><p><Placeholder>company files pending</Placeholder></p><button disabled>Not yet available</button></div>)}</section></main>;
  return <main><PageHero eyebrow={eyebrow} title={title} intro={intro}/><section className="section editorial"><div><h2>Company review required</h2><p>This page is intentionally structured without invented facts. Replace the review markers with verified company data, original photography, responsible personnel and dated evidence.</p></div><div className="fact-sheet"><p><span>Legal company name</span><Placeholder>{company.legalName}</Placeholder></p><p><span>Factory location</span><Placeholder>{company.address}</Placeholder></p><p><span>Certifications</span><Placeholder>verified certificate names and dates</Placeholder></p><p><span>Production capability</span><Placeholder>verified lines and annual capacity</Placeholder></p></div></section><Rfq compact/></main>;
}

function Insights({ slug }: { slug?: string }) { const article = articles.find(a => a.slug === slug); if (article) return <main><article className="article-page"><span className="eyebrow">{article.type}</span><h1>{article.title}</h1><p className="lead">{article.summary}</p><div className="article-meta">Placeholder editorial draft · Technical review required · Updated July 2026</div><h2>Start with production context</h2><p>A useful industrial recommendation begins with the exact substrate, process conditions, finishing steps and end-use requirements. Product names alone are not enough to predict production performance.</p><h2>Build a comparable trial</h2><p>Document the sample identifier, press settings, ambient conditions, substrate batch, color target, drying observations and resistance results. Keep the approved sample and the test record together.</p><div className="review-note"><b>Editorial review checkpoint</b><p>This sample article demonstrates structure and tone. A qualified company specialist must replace it with original, evidence-backed guidance before publication.</p></div></article><Rfq compact/></main>; return <main><PageHero eyebrow="INSIGHTS" title="Technical answers, written for buyers." intro="Selection guides, application notes and procurement resources designed to be clear, attributable and easy to verify."/><section className="section article-grid">{articles.map(a => <Link key={a.slug} href={`/insights/${a.slug}`}><span>{a.type}</span><h3>{a.title}</h3><p>{a.summary}</p><b>Read guide <Arrow /></b></Link>)}</section></main>; }

export function SitePage({ route }: { route: string }) {
  const product = products.find(p => route.endsWith(`/${p.slug}`));
  const application = applications.find(a => route === `/applications/${a.slug}`);
  const insightSlug = route.startsWith("/insights/") ? route.split("/").pop() : undefined;
  let page: React.ReactNode = <StandardPage route={route}/>;
  if (route === "/") page = <Home/>;
  else if (route === "/products") page = <ProductsPage/>;
  else if (product) page = <ProductDetail product={product}/>;
  else if (route === "/applications") page = <ApplicationsPage/>;
  else if (application) page = <ApplicationDetail item={application}/>;
  else if (route === "/insights" || insightSlug) page = <Insights slug={insightSlug}/>;
  const schema = { "@context": "https://schema.org", "@type": route === "/" ? "Organization" : product ? "Product" : insightSlug ? "Article" : "WebPage", name: product?.name || articles.find(a=>a.slug===insightSlug)?.title || company.brand, ...(product ? { description: product.use, sku: product.code, brand: {"@type":"Brand", name:company.brand} } : {}) };
  return <><Header/>{page}<Footer/><script type="application/ld+json" dangerouslySetInnerHTML={{__html: JSON.stringify(schema)}}/></>;
}
